### ISSUE TITLE
ESP8266 i2c issue

### ISSUE THREAD

**Issue by asetyde** [stevemarple/HIH61xx#1]
Hi, I'm using Arduino/esp8266 library with my esp board and hih6121 but can't find device on i2c
Sampling started
RH: 655.35 %
Ambient: 327.67 deg C
Status: 5
Sampling started
RH: 655.35 %
Ambient: 327.67 deg C
Status: 5
Sampling started
RH: 655.35 %
Ambient: 327.67 deg C
Status: 5
Sampling started
RH: 655.35 %
Ambient: 327.67 deg C
Status: 5
Sampling started
RH: 655.35 %
Ambient: 327.67 deg C
Status: 5
Sampling started
RH: 655.35 %
Ambient: 327.67 deg C
Status: 5
Sampling started
RH: 655.35 %
Ambient: 327.67 deg C
Status: 5

**Comment by 8mccm8** [comment]
Hi,
same result
23:05:24.675 -> Sampling started (using Wire library)
23:05:24.675 -> Error when powering up: 2
23:05:24.675 -> RH: 655.35 %
23:05:24.675 -> Ambient: 327.67 deg C
23:05:24.675 -> Status: 5

**Comment by stevemarple** [comment]
https://github.com/esp8266/Arduino/issues/4136 was closed by @asetyde so I assume this is resolved.
